### ISSUE TITLE
Fix collision boxes

### ISSUE THREAD

**Issue by tomcraven** [marc-hugh-tom/ship#13]
Arcade collision boxes cannot be rotated, this means that they are off by quite a bit when the ship rotates its position. We need to fix this, there are a few options we could go down:
- Controlling collision detection ourselves
- Having 2 collision boxes, one at the base of the ship and another at the tip, we would need to control the position/dimensions of them ourselves
- Investigate P2 physics again. There's already been some investigation into P2. Pros - rotated box collision detection, circle collision detection for future asteroids (arcade only supports rect). Cons - difficult to modify objects position (though could look into game.camera.follow), apparently performs badly on mobile (untested).
- Look into another physics engine

**Comment by marc-jones** [comment]
Fixed with #18
