### ISSUE TITLE
Install Phaser via npm?

### ISSUE THREAD

**Issue by hughgrigg** [marc-hugh-tom/ship#25]
Rather than having Phaser brought in as a sub-repository, how about making it project a dependency via npm? I think that's the more standard way of doing it. Would mean we don't need the `--recursive` on clone and aren't keeping Phaser code in our source control.

I'll make a PR if you guys agree.

**Comment by marc-jones** [comment]
I quite like that if someone pulls a local copy at the moment that they don't need anything installed except a lightweight web server, which Unix users have courtesy of Python. If we use npm we're making Node a dependency.

**Comment by hughgrigg** [comment]
Yeah fair enough!
