### ISSUE TITLE
Create basic asteroid and make them spawn

### ISSUE THREAD

**Issue by marc-jones** [marc-hugh-tom/ship#4]
The basic asteroids shouldn't be affected by the gravity of the black hole. Instead, they have a certain unchanging velocity as they move across the screen.

To add variety, they could come in multiple sizes and have a slight spin to them.

They should spawn off screen and should always have a negative x component to their velocity. i.e. they can't approach the rocket from the rear and chase it.

When the asteroid leaves the screen, it should be destroyed.

**Comment by tomcraven** [comment]
https://github.com/marc-hugh-tom/ship/pull/15
